from Elementos_quimicos.First_Period.Hydrogen import HydWin
from Elementos_quimicos.First_Period.Helium import HelWin
from Elementos_quimicos.Second_Period.Lithium import LitWin
from Elementos_quimicos.Second_Period.Beryllium import BerWin
from Elementos_quimicos.Second_Period.Boron import BorWin
from Elementos_quimicos.Second_Period.Carbon import CarWin
from Elementos_quimicos.Second_Period.Nitrogen import NitWin
from Elementos_quimicos.Second_Period.Oxygen import OxyWin
from Elementos_quimicos.Second_Period.Fluorine import FluWin
from Elementos_quimicos.Second_Period.Neon import NeoWin
from Elementos_quimicos.Third_Period.Sodium import SodWin
from Elementos_quimicos.Third_Period.Magnesium import MagWin
from Elementos_quimicos.Third_Period.Aluminum import AluWin
from Elementos_quimicos.Third_Period.Silicon import SilWin
from Elementos_quimicos.Third_Period.Phosphorus import PhoWin
from Elementos_quimicos.Third_Period.Sulfur import SulWin
from Elementos_quimicos.Third_Period.Chlorine import ChlWin
from Elementos_quimicos.Third_Period.Argon import ArgWin
from Elementos_quimicos.Fourth_Period.Potassium import PotWin
from Elementos_quimicos.Fourth_Period.Calcium import CalWin
from Elementos_quimicos.Fourth_Period.Scandium import ScaWin
from Elementos_quimicos.Fourth_Period.Titanium import TitWin
from Elementos_quimicos.Fourth_Period.Vanadium import VanWin

